name: Bug Report
description: Report a bug or issue with the documentation site
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us resolve the issue.

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: What type of bug are you reporting?
      options:
        - Broken link
        - Build error
        - Rendering issue
        - Navigation problem
        - Search not working
        - Performance issue
        - Styling/CSS issue
        - Mobile responsiveness
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the bug
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: input
    id: affected-url
    attributes:
      label: Affected URL
      description: The documentation page where the bug occurs
      placeholder: https://brookside-buisness-intelligence.github.io/ams-docs/guide/...
    validations:
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where did you encounter this bug?
      options:
        - Production site (GitHub Pages)
        - Local development (npm run docs:dev)
        - Production build (npm run docs:build)
        - Preview (npm run docs:preview)
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile browser
        - Other
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Error Messages
      description: Add screenshots or paste error messages
      placeholder: Drag and drop images here or paste error messages
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other relevant information
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have checked the latest version of the documentation
          required: false
